export class SkuSchemaDto {
  constructor() {
    this.JoiningKey = "";
    this.Retailer = "";
    this.Manufacturer = "";
    this.Brand = "";
    this.Platform = "";
    this.Category = "";
    this.Segment = "";
    this.SubSegment = "";
    this.SubSegment1 = "";
    this.SubSegment2 = "";
    this.SubSegment3 = "";
    this.SubSegment4 = "";
    this.SubSegment5 = "";
    this.SubSegment6 = "";
    this.SubSegment7 = "";
    this.SubSegment8 = "";
    this.SubSegment9 = "";
    this.SubSegment10 = "";
    this.SubSegment11 = "";
    this.SubSegment12 = "";
    this.SubSegment13 = "";
    this.SubSegment14 = "";
    this.SubSegment15 = "";
    this.SubSegment16 = "";
    this.SubSegment17 = "";
    this.SubSegment18 = "";
    this.SubSegment19 = "";
    this.TagsAll = "";
    this.ProductCategory = "";
    this.ProductBrand = "";
    this.ProductName = "";
    this.ProductRating = 0;
    this.ProductRatingsCount = 0;
    this.RatingsXReviews = 0;
    this.ProductReviewsCount = 0;
    this.Sku = "";
    this.Upc = "";
    this.ProductModelNumber = "";
    this.ProductUrl = "";
    this.UniqId = "";
    this.CrawlTimestamp = "";
    this.ProductPrice = 0;
    this.SkuProductId = "";
    this.Pageurl = "";
    this.Url = "";
    this.Market = "";
    this.ProductCurrency = "";
    this.ProductAvailableInventory = 0;
    this.ProductDescription = "";
    this.ProductTags = "";
    this.ProductContents = "";
    this.ProductImageUrl = "";
    this.locationId = "";
    this.productId = "";
    this.categoryId = "";
    this.createdBy = "";
  }
  JoiningKey: string;
  Retailer: string;
  Manufacturer: string;
  Brand: string;
  Platform: string;
  Category: string;
  Segment: string;
  SubSegment: string;
  SubSegment1: string;
  SubSegment2: string;
  SubSegment3: string;
  SubSegment4: string;
  SubSegment5: string;
  SubSegment6: string;
  SubSegment7: string;
  SubSegment8: string;
  SubSegment9: string;
  SubSegment10: string;
  SubSegment11: string;
  SubSegment12: string;
  SubSegment13: string;
  SubSegment14: string;
  SubSegment15: string;
  SubSegment16: string;
  SubSegment17: string;
  SubSegment18: string;
  SubSegment19: string;
  TagsAll: string;
  ProductCategory: string;
  ProductBrand: string;
  ProductName: string;
  ProductRating: number;
  ProductRatingsCount: number;
  RatingsXReviews: number;
  ProductReviewsCount: number;
  Sku: string;
  Upc: string;
  ProductModelNumber: string;
  ProductUrl: string;
  UniqId: string;
  CrawlTimestamp: string;
  ProductPrice: number;
  SkuProductId: string;
  Pageurl: string;
  Url: string;
  Market: string;
  ProductCurrency: string;
  ProductAvailableInventory: number;
  ProductDescription: string;
  ProductTags: string;
  ProductContents: string;
  ProductImageUrl: string;
  createdBy: string;
  productId: string;
  locationId: string;
  categoryId: string;
}
